<?php
// @author Dino Simeon M. Madarang <dmadarang@gmail.com>

define('BSPKEYRATES_US_DOLLAR_COLUMN', 13);

define('BSPKEYRATES_PH_PESO_COLUMN', 15);

define('BSPKEYRATES_TABLE_ARRAY_SIZE', 15);

define('BSPKEYRATES_COUNTRY_CODE', 5);

define('BSPKEYRATES_UNIT', 7);

define('BSPKEYRATES_SYMBOL', 9);

define('BSPKEYRATES_ROW_NUMBER', 3);

define('BSPKEYRATES_MINIMUN_REFRESH', 300);

/**
* Display help and module information
* @param section which section of the site we're displaying help
* @return help text for section
*/
function bspkeyrates_help($section='') {
  $output = '';
  switch ($section) {
    case "admin/help#bspkeyrates":
      $output = '<p>'.  t("Converts Bangko Sentral ng Pilipinas Exchange Rate bulletin (HTML Table) to a drupal page"). '</p>';
      break;
  }

  return $output;
} // end bspkeyrates_help


function bspkeyrates_block_info() {
  $blocks['bspkeyrates_block'] = array(
    'info' => t('BSP Key Rates block'),
  );

  return $blocks;
}


/**
* Generate HTML for the BSP Exchange block
* @param delta offset
* @returns block HTML
*/
function bspkeyrates_block_view($delta=0) {
  drupal_add_css(drupal_get_path('module', 'bspkeyrates') .'/bspkeyrates.css');

  $block['subject'] = 'BSP Key Rates';

  $dollarpeso = variable_get('bspkeyrates_phil_peso', '');
  if ($dollarpeso !== "") {
    $dollarpeso = 'US$ 1.00 = ' . $dollarpeso;
  }

  $lastupdate = variable_get('bspkeyrates_datetime', '');
  if ($lastupdate !== "") {
    $block['subject'] = 'BSP Key Rates ' . $lastupdate;
    $lastupdate = 'as of ' . $lastupdate;
  }
  else {
    $lastupdate = 'No updates';
  }

  $block['content'] = theme('bspkeyrates_dollar_peso', array('dollarpeso' => $dollarpeso,
                            'lastupdate' => $lastupdate));
  return $block;
} // end bspkeyrates_block_view


function bspkeyrates_theme() {
  return array(
    'bspkeyrates_wrapper' => array(
      'variables' => array('content' => NULL),
      'template' => 'bspkeyrates-wrapper',
    ),
    'bspkeyrates_dollar_peso' => array(
      'variables' => array('dollarpeso' => NULL, 'lastupdate' => NULL),
      'template' => 'bspkeyrates-dollar-peso',
    ),
  );
}

function bspkeyrates_fetch() {
  $sourceurl = variable_get('bspkeyrates_source_url','http://www.bsp.gov.ph/');
  $source    = file_get_contents($sourceurl);

  if (!class_exists('tableExtractor')) {
    include_once 'table-extractor.php';
  }

  if ($source) {
  //  watchdog('bspkeyrates', t('BSP Exchange') . ' ' . $sourceurl . ' downloaded');

    //variable_get('bspkeyrates_last_update', $exchangerate[12]);
    variable_set('bspkeyrates_checked', time());

    // Get start and end position of the US - Peso row in the key rates table
	  $startPosition = stripos($source, "Key Rates") + 11;
	  $endPosition   = stripos($source, "Repo Rate") - 112;
	  $length        = $endPosition - $startPosition;

    $table = substr($source, $startPosition, $length) . "</table>";

    $tx = new tableExtractor;
    $tx->source = $table;
    $tx->stripTags = true;
    $tableArray = @$tx->extractTable();
    if ($tableArray) {
      $dateInArray = array_keys($tableArray[1]);
      variable_set('bspkeyrates_datetime', $dateInArray[0]);
      $arrayKeyForPeso = $dateInArray[1];
      variable_set('bspkeyrates_phil_peso', $tableArray[1][$arrayKeyForPeso]);
    }
    else {
	    drupal_mail("bspkeyrates", variable_get('bspexchange_notify_email','webtechofficer@sunstar.com.ph'),
                  "bspkeyrates not updated", "bspkeyrates data not updated.");
	    watchdog('bspkeyrates', t('BSP Exchange rate bulletin has been updated.'), WATCHDOG_WARNING);
    }
  }
  else {
    drupal_mail("bspkeyrates", variable_get('bspexchange_notify_email','webtechofficer@sunstar.com.ph'),
                "bspkeyrates not updated", "bspkeyrates data not updated.");
    watchdog('bspkeyrates', t('Failed to refresh BSP Exchange rate bulletin.'), WATCHDOG_WARNING);
  }


  $feed['url'] = variable_get('bspexchange_bulletin_source_url', 'http://www.bsp.gov.ph/statistics/sdds/exchrate.htm');

  $tx = new tableExtractor;
  $tx->stripTags = true;
  $tx->startRow = 3;
  $tx->startCol = 2;

  $tx->source = '';

  // Generate conditional GET headers.
  $headers = array();
  if (isset($feed['etag'])) {
    $headers['If-None-Match'] = $feed['etag'];
  }
  if (isset($feed['modified'])) {
    $headers['If-Modified-Since'] = gmdate('D, d M Y H:i:s', $feed['modified']) .' GMT';
  }

  $headers['method'] = 'GET';
  $headers['User-Agent'] = "User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1)\r\n\r\n";
  // Request feed.
  $result = drupal_http_request($feed['url'], $headers);

  // Process HTTP response code.
  // echo $result->code;
  switch ($result->code) {
    case 301:
      $feed['url'] = $result->redirect_url;
      watchdog('bspkeyrates', t('Updated URL to %url.', array('%url' => $feed['url'])));
    case 200:
    case 302:
    case 304:
    case 307:
      // Filter the input data:
      if ($result->data) {
        if (isset($result->headers['Last-Modified'])) {
          $modified = strtotime($result->headers['Last-Modified']);
        }
        $tx->source = $result->data;
        watchdog('bspkeyrates', t('There is new content from %site.', array('%site' => $feed['url'])));
        drupal_set_message(t('There is new syndicated content from %site.', array('%site' => $feed['url'])));
      }
      break;
    default:
      watchdog('bspkeyrates', t('The bspkeyrates from %site seems to be broken, due to "%error".',
                array('%site' => $feed['url'], '%error' => $result->code .' '. $result->error)), WATCHDOG_WARNING);
  }

  if ($tx->source) {
    watchdog('bspkeyrates', t('BSP Exchange') . ' ' . $feed['url'] . ' downloaded');

    // Replace contents
    db_query('DELETE FROM {bspexchange}');

    $tableArray = @$tx->extractTable();

    $rows = array();

    // $tableArray contains the table rows of http://www.bsp.gov.ph/statistics/sdds/exchrate.htm.
    // The following loop extracts the rows which contains foriegn currency to peso data.
    // Usually BSP modifies the columns of the key rates. When this happens, you may need to modify
    // the indexes of $exchangerate to properly retrieve the key rates.

    //var_dump($tableArray);
    //exit();

    foreach ($tableArray as $exchangerate) {
      if ($exchangerate[3] == "Reference Exchange Rate Bulletin") {
        variable_set('bspexchange_last_update', $exchangerate[13]);
        // if 13 is empty, use 12 (May 25, 2015 html)
      }

      //  var_dump($exchangerate);

      if (count($exchangerate) >= BSPKEYRATES_TABLE_ARRAY_SIZE and
          strlen($exchangerate[BSPKEYRATES_ROW_NUMBER]) > 0 and
          strlen($exchangerate[BSPKEYRATES_COUNTRY_CODE]) > 0 and
          strlen($exchangerate[BSPKEYRATES_UNIT]) > 0 and
          strlen($exchangerate[BSPKEYRATES_SYMBOL]) > 0 and
          strlen($exchangerate[BSPKEYRATES_US_DOLLAR_COLUMN]) > 0
          and strlen($exchangerate[BSPKEYRATES_PH_PESO_COLUMN]) > 0) {

//      if (count($exchangerate) > 0) {

        db_query("DELETE FROM {bspexchange} WHERE bsp_country =:bsp_country", array(':bsp_country' => $exchangerate[BSPKEYRATES_COUNTRY_CODE]));

 			  if ($exchangerate[BSPKEYRATES_UNIT] == "POUND") {
          db_query("INSERT INTO {bspexchange} (bsp_country, bsp_unit, bsp_symbol, bsp_us_dollar, bsp_phil_peso)
                    VALUES (:bsp_country, :bsp_unit, :bsp_symbol, :bsp_us_dollar, :bsp_phil_peso)",
                  array(
                  ':bsp_country' => $exchangerate[BSPKEYRATES_COUNTRY_CODE],
                  ':bsp_unit' => $exchangerate[BSPKEYRATES_UNIT],
                  ':bsp_symbol' => "GBP",
                  ':bsp_us_dollar' => $exchangerate[BSPKEYRATES_US_DOLLAR_COLUMN],
                  ':bsp_phil_peso' => $exchangerate[BSPKEYRATES_PH_PESO_COLUMN]));

			  }
        else {
          db_query("INSERT INTO {bspexchange} (bsp_country, bsp_unit, bsp_symbol, bsp_us_dollar, bsp_phil_peso)
                  VALUES (:bsp_country, :bsp_unit, :bsp_symbol, :bsp_us_dollar, :bsp_phil_peso)",
                  array(
                  ':bsp_country' => $exchangerate[BSPKEYRATES_COUNTRY_CODE],
                  ':bsp_unit' => $exchangerate[BSPKEYRATES_UNIT],
                  ':bsp_symbol' => trim($exchangerate[BSPKEYRATES_SYMBOL]),
                  ':bsp_us_dollar' => $exchangerate[BSPKEYRATES_US_DOLLAR_COLUMN],
                  ':bsp_phil_peso' => $exchangerate[BSPKEYRATES_PH_PESO_COLUMN]));

        }
      }
      elseif (count($exchangerate) == (BSPKEYRATES_TABLE_ARRAY_SIZE -1) and
          strlen($exchangerate[BSPKEYRATES_ROW_NUMBER -1]) > 0 and
          strlen($exchangerate[BSPKEYRATES_COUNTRY_CODE -1]) > 0 and
          strlen($exchangerate[BSPKEYRATES_UNIT -1]) > 0 and
          strlen($exchangerate[BSPKEYRATES_SYMBOL -1]) > 0 and
          strlen($exchangerate[BSPKEYRATES_US_DOLLAR_COLUMN -1]) > 0
          and strlen($exchangerate[BSPKEYRATES_PH_PESO_COLUMN -1]) > 0) {

        if ($exchangerate[BSPKEYRATES_UNIT -1] == "POUND") {
          db_query("INSERT INTO {bspexchange} (bsp_country, bsp_unit, bsp_symbol, bsp_us_dollar, bsp_phil_peso)
                    VALUES (:bsp_country, :bsp_unit, :bsp_symbol, :bsp_us_dollar, :bsp_phil_peso)",
                  array(
                  ':bsp_country' => $exchangerate[BSPKEYRATES_COUNTRY_CODE -1],
                  ':bsp_unit' => $exchangerate[BSPKEYRATES_UNIT -1],
                  ':bsp_symbol' => "GBP",
                  ':bsp_us_dollar' => $exchangerate[BSPKEYRATES_US_DOLLAR_COLUMN -1],
                  ':bsp_phil_peso' => $exchangerate[BSPKEYRATES_PH_PESO_COLUMN -1]));
			  }
        else {
          db_query("INSERT INTO {bspexchange} (bsp_country, bsp_unit, bsp_symbol, bsp_us_dollar, bsp_phil_peso)
                  VALUES (:bsp_country, :bsp_unit, :bsp_symbol, :bsp_us_dollar, :bsp_phil_peso)",
                  array(
                  ':bsp_country' => $exchangerate[BSPKEYRATES_COUNTRY_CODE -1],
                  ':bsp_unit' => $exchangerate[BSPKEYRATES_UNIT -1], 
                  ':bsp_symbol' => trim($exchangerate[BSPKEYRATES_SYMBOL -1]),
                  ':bsp_us_dollar' => $exchangerate[BSPKEYRATES_US_DOLLAR_COLUMN -1],
                  ':bsp_phil_peso' => $exchangerate[BSPKEYRATES_PH_PESO_COLUMN -1]));
        }
      }
    }

    if (isset($tableArray[48])) {
      /// Parse date from  this line : '***   Asian Time Closing Rates as of 9/23/2008';
      if (isset($tableArray[48][6]) && 0 !== strpos($tableArray[48][6],'as of')) {
        variable_set('bspexchange_closing_datetime', substr($tableArray[48][6], strpos($tableArray[48][6],'as of') + 5));
        variable_set('bspexchange_checked', time());
      } else {
        drupal_mail("bspkeyrates", variable_get('bspexchange_notify_email','webtechofficer@sunstar.com.ph'),
                    "bspkeyrates not updated", "bspkeyrates data not updated.");
      }
    }
    watchdog('bspkeyrates', t('BSP Exchange rate bulletin has been updated.'));
  }
  else {
    drupal_mail("bspkeyrates", variable_get('bspexchange_notify_email','webtechofficer@sunstar.com.ph'),
                "bspkeyrates not updated", "bspkeyrates data not updated.");
    watchdog('bspkeyrates', t('Failed to refresh BSP Exchange rate bulletin.'), WATCHDOG_WARNING);
  }
}


function bspkeyrates_admin_settings() {

  $period = drupal_map_assoc(array(BSPKEYRATES_MINIMUN_REFRESH, 3600, 7200, 14400,
                                   21600, 28800, 43200, 64800, 86400), 'format_interval');

  $form['bspkeyrates_source_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Source URL'),
    '#size' => 80,
    '#maxlength' => 255,
    '#default_value' => variable_get('bspkeyrates_source_url', 'http://www.bsp.gov.ph/'),
    '#description' => t('HTML Table source URL')
  );

  $form['bspexchange_bulletin_source_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Exchange Rate Bulleting Source URL'),
    '#size' => 80,
    '#maxlength' => 255,
    '#default_value' => variable_get('bspexchange_bulletin_source_url', 'http://www.bsp.gov.ph/statistics/sdds/exchrate.htm'),
    '#description' => t('Exchange Rate Bulletin HTML Table source URL. Default: http://www.bsp.gov.ph/statistics/sdds/exchrate.htm')
  );

  $form['bspexchange_notify_email'] = array(
    '#type' => 'textfield',
    '#title' => t('Notify'),
    '#size' => 50,
    '#maxlength' => 255,
    '#default_value' => variable_get('bspexchange_notify_email', 'webtechofficer@sunstar.com.ph'),
    '#description' => t('Send email to this address if error occurs')
  );

  $form['bspkeyrates_refresh'] = array('#type' => 'select',
    '#title' => t('Update interval'),
    '#default_value' => variable_get('bspkeyrates_refresh', 43200),
    '#options' => $period,
    '#description' => t('The refresh interval indicating how often you want to update this feed. Requires crontab.'),
  );

  $form['bspkeyrates_update'] = array('#type' => 'button', '#value' => t('Update'));

  if (isset($_POST['op']) && $_POST['op'] == 'Update') {
    bspkeyrates_fetch();
    drupal_set_message(t('The BSP Exchange Rate Bulletin has been updated.'), 'status');
  }

  return system_settings_form($form);
}

/**
 * Implementation of hook_menu().
 */
function bspkeyrates_menu() {
  $items = array();

  $items['admin/config/services/bspkeyrates'] = array(
    'title' => t('BSP Key Rates Settings'),
    'description' => t('BSP Key Rates settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bspkeyrates_admin_settings'),
    'access arguments' => array('administer bspkeyrates'),
  );

  $items['bspkeyrates/bulletin'] = array(
    'title' => 'BSP Exchange Rate bulletin',
    'page callback' => 'bspexchange_list',
    'access arguments' => array('access bspkeyrates'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function bspkeyrates_permission() {
  return array(
    'administer bspkeyrates' => array(
      'title' => t('Administer bspkeyrates'),
    ),
    'access bspkeyrates' => array(
      'title' => t('View bspkeyrates'),
    ),
  );
}

/**
 * Implementation of hook_cron().
 *
 * Update bulletin once their refresh interval has elapsed.
 */
function bspkeyrates_cron() {
  $refresh = variable_get('bspkeyrates_refresh', BSPKEYRATES_MINIMUN_REFRESH);
  $checked = variable_get('bspkeyrates_checked', 0);

  if (($refresh + $checked) < time()) {
    bspkeyrates_fetch();
  }

}

/**
 * Displays the BSP Exchange Rate bulletin
 *
 */
function bspexchange_list() {

  $rows = array();

  $sql = 'SELECT bsp_country,
                 bsp_unit,
                 bsp_us_dollar,
                 bsp_phil_peso
          FROM {bspexchange}';

  $res = db_query($sql);

  foreach ($res as $record) {
    $rows[] = array($record->bsp_country, $record->bsp_unit,
                    $record->bsp_us_dollar, $record->bsp_phil_peso);
  }

  $header = array('Country', 'Unit', 'US Dollar Equivalent', 'PHIL. PESO');

  $output = variable_get('bspkeyrates_datetime', '') .
            theme('table', array('header' => $header, 'rows' => $rows)) .
            'Source : '. variable_get('bspexchange_source_text', 'Bangko Sentral ng Pilipinas');
  return theme('bspkeyrates_wrapper', array('content' => $output));

}

